[package]
name = "ray-tracing"
version = "0.1.0"
authors = []
edition = "2021"

[dependencies]
rand = { version = "0.8", features = ["small_rng"] }

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
